services:
  frontend:
    build:
      context: ./
      target: prod
    ports:
      - "${APP_PORT}:8030"
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE:-myawesomememe}
      MONGO_PASSWORD: ${MONGO_PASSWORD:-}
    expose:
      - "27017"
    volumes:
      - mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

volumes:
  mongo_data:
    driver: local
