services:
  frontend:
    build:
      context: ./
      target: dev
    ports:
      - "${APP_PORT:-8030}:8030"
      - "${APP_DEBUG_PORT:-9229}:9229"
    volumes:
      - .:/srv/app:rw
    depends_on:
      - mongo

  mongo:
    ports:
      - "27170:27017"